export const ADD_INGREDIENT = "ADD_INGREDIENT";
export const REMOVE_INGREDIENT = "REMOVE_INGREDIENT";
export const ADD_PRICE = "ADD_PRICE";
export const REMOVE_PRICE = "REMOVE_PRICE";
export const RESET_PRICE = "RESET_PRICE";

export const SAVE_INGREDIENTS = "SAVE_INGREDIENTS";
export const FETCH_FAILURE = "FETCH_FAILURE";

export const SEND_DATA = "SEND_DATA";
export const PURCHASE_START = "PURCHASE_START";
export const PURCHASE_SUCCESS = "PURCHASE_SUCCESS";
export const PURCHASE_FAIL = "PURCHASE_FAIL";

export const FETCH_START = "FETCH_START";
export const FETCH_SUCCESS = "FETCH_SUCCESS";
export const FETCH_FAIL = "FETCH_FAIL";

export const ORDER_UNPURCHASED = "ORDER_UNPURCHASED";

export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const SET_REDIRECT_PATH = "SET_REDIRECT_PATH";

export const SET_TOKEN = "SET_TOKEN";
